package.json
scripts/deploy.sh

deploy script added

---

packages/vite-plugin-hash-csp/package.json

vite-plugin-hash-csp-0.3.0

---

packages/vite-plugin-hash-csp/package.json

vite-plugin-hash-csp-0.4.0

---

packages/vite-plugin-hash-csp/package.json

vite-plugin-hash-csp-0.5.0

---

packages/vite-plugin-hash-csp/package.json

- Select only dist and license in package.json

Minimise package size

---

packages/vite-plugin-hash-csp/package.json

vite-plugin-hash-csp-0.6.0

---

packages/vite-plugin-hash-csp/rollup.config.mjs

- Remove sourcemaps to reduce bundle size

chore: remove sourcemaps

---

packages/vite-plugin-hash-csp/package.json

vite-plugin-hash-csp-0.6.1

---

packages/vite-plugin-hash-csp/package.json
packages/vite-plugin-hash-csp/rollup.config.mjs
pnpm-lock.yaml

- Fix peer deps in package json
- add terser to minify outputted bundle

Fix: Peer Deps and Bundle optimisations

---

packages/vite-plugin-hash-csp/package.json

vite-plugin-hash-csp-0.6.2

---

packages/vite-plugin-csp-guard/package.json

Is stable for SPA's. Big API changes are unlikely going forward.
SSR support maybe coming soon in v2.
More testing and better support for lazy loading coming soon

vite-plugin-csp-guard-1.0.0

---

apps/docs/pages/index.mdx

- Update name from old package

fix:  name change for docs

---

apps/docs/theme.config.jsx

chore: fix titles

---

packages/vite-plugin-csp-guard/package.json

vite-plugin-csp-guard-1.1.0

---

.github/ISSUE_TEMPLATE/react-bug-report.md

Add a React specific issue template

Update issue templates

---

packages/vite-plugin-csp-guard/package.json

- exports field in the package.json

fix: exports package.json field

---

packages/vite-plugin-csp-guard/package.json

vite-plugin-csp-guard-1.1.1

---

apps/react/vite.config.ts
packages/vite-plugin-csp-guard/src/policy/createPolicy.ts
packages/vite-plugin-csp-guard/tests/policies.test.ts

- Remove wrapping wildcard with quotes
- Add tests for policy creation

Fix: policy creation

---

packages/vite-plugin-csp-guard/package.json

vite-plugin-csp-guard-1.1.2

---

packages/vite-plugin-csp-guard/package.json

vite-plugin-csp-guard-1.1.3

---

.github/pull_request_template.md
apps/docs/pages/guides/spa.mdx

- Fixing typo in documentation

fix: typo in docs

---

apps/docs/pages/api-docs.mdx

- Update default on documenation

chore: update default for build in api docs

---

.github/workflows/release.yml
.github/workflows/triage.yml
package.json
packages/vite-plugin-csp-guard/package.json
packages/vite-plugin-csp-guard/rollup.config.mjs

feat: add cjs support

---

.github/dependabot.yml
apps/docs/package.json
apps/emotion/package.json
apps/less/package.json
apps/mui/package.json
apps/preact-app/package.json
apps/react/package.json
apps/remix-spa/package.json
apps/remix/package.json
apps/scss/package.json
apps/solid-app/package.json
apps/stylus/package.json
apps/svelte-app/package.json
apps/tailwind/package.json
apps/tailwind/vite.config.ts
apps/vue-app/package.json
packages/eslint-config/package.json
packages/vite-plugin-csp-guard/package.json
pnpm-lock.yaml

- Consolidate TS version
- Add dependabot config

chore: dep management

---

.github/workflows/release.yml
packages/csp-toolkit/package.json

Fix: release

---

.github/workflows/release.yml
packages/csp-toolkit/package.json
scripts/version-has-changed.sh

fix: release workflow

---

packages/vite-plugin-csp-guard/package.json

- Releasing V2
[Migration Guide here](https://vite-csp.tsotne.co.uk/migrations/v2)

Release: Vite Plugin CSP Guard V2

---

packages/csp-toolkit/package.json
scripts/release.sh

- Bump CSP Toolkit version
- Update release script to commit

Release: csp-toolkit v1.1.1

---

packages/vite-plugin-csp-guard/package.json

- Maily documentation changes, nothing to do with functionality

chore(release): bump vite-plugin-csp-guard to v2.0.1

---

packages/csp-toolkit/package.json

chore(release): bump csp-toolkit to v1.3.0

---

package.json
packages/vite-plugin-csp-guard/package.json
pnpm-lock.yaml

Release/vite plugin csp guard 2.0.2

---

packages/vite-plugin-csp-guard/src/index.ts
packages/vite-plugin-csp-guard/src/utils.ts

- Check vite version [via this feature](https://github.com/vitejs/vite/pull/8456)
Doesn't really work with monorepo's but its the best we have so far [until this goes in](https://github.com/vitejs/vite/pull/19355)

fix: getting version

---

packages/vite-plugin-csp-guard/package.json

chore(release): bump vite-plugin-csp-guard to v2.0.3

---

packages/vite-plugin-csp-guard/package.json

chore(release): bump vite-plugin-csp-guard to v2.0.4

---

packages/vite-plugin-csp-guard/package.json

chore(release): bump vite-plugin-csp-guard to v2.1.0

---

packages/vite-plugin-csp-guard/package.json
packages/vite-plugin-csp-guard/src/transform/lazy.ts

Stabilises `generateViteDepMap` for SRI usage
Use the vite bundle output as much as possible

fix/solidify vue-router fixes

---

packages/vite-plugin-csp-guard/package.json

chore(release): bump vite-plugin-csp-guard to v2.1.1

---

.vscode/settings.json
apps/emotion/package.json
apps/emotion/vite.config.ts
apps/less/package.json
apps/less/vite.config.ts
apps/mui/package.json
apps/mui/vite.config.ts
apps/preact-app/package.json
apps/preact-app/vite.config.ts
apps/react/package.json
apps/react/vite.config.ts
apps/remix-spa/package.json
apps/scss/package.json
apps/scss/vite.config.ts
apps/solid-app/package.json
apps/stylus/package.json
apps/stylus/vite.config.ts
apps/svelte-app/package.json
apps/tailwind/package.json
apps/tailwind/vite.config.ts
apps/tailwind4/package.json
apps/tailwind4/vite.config.ts
apps/vite6/package.json
apps/vue-app/package.json
apps/vue-app/vite.config.ts
apps/vue-router/package.json
package.json
packages/typescript-config/node.json
pnpm-lock.yaml
pnpm-workspace.yaml

Builds were breaking over TS issues. Unified vite version with catalog and gave type assertions to vite configs

chore: fix builds
